---

services:
  hapifhir:
    image: hapiproject/hapi:latest
    container_name: hapifhir
    ports:
      - 8888:8888
    volumes:
      - ./application.yaml:/app/config/application.yaml
    restart: unless-stopped
  jbpmserver:
    image: jboss/jbpm-server-full:latest
    container_name: jbpmserver
    volumes:
        -  C:/Users/isabo/.m2/repository:/opt/jboss/wildfly/bin/repositories/kie
    ports:
      - 8080:8080
      - 8001:8001
    restart: unless-stopped


